// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XPREDICTOR3_H
#define XPREDICTOR3_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xpredictor3_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_ctrl_BaseAddress;
} XPredictor3_Config;
#endif

typedef struct {
    u32 Bus_ctrl_BaseAddress;
    u32 IsReady;
} XPredictor3;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XPredictor3_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XPredictor3_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XPredictor3_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XPredictor3_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XPredictor3_Initialize(XPredictor3 *InstancePtr, u16 DeviceId);
XPredictor3_Config* XPredictor3_LookupConfig(u16 DeviceId);
int XPredictor3_CfgInitialize(XPredictor3 *InstancePtr, XPredictor3_Config *ConfigPtr);
#else
int XPredictor3_Initialize(XPredictor3 *InstancePtr, const char* InstanceName);
int XPredictor3_Release(XPredictor3 *InstancePtr);
#endif

void XPredictor3_Start(XPredictor3 *InstancePtr);
u32 XPredictor3_IsDone(XPredictor3 *InstancePtr);
u32 XPredictor3_IsIdle(XPredictor3 *InstancePtr);
u32 XPredictor3_IsReady(XPredictor3 *InstancePtr);
void XPredictor3_EnableAutoRestart(XPredictor3 *InstancePtr);
void XPredictor3_DisableAutoRestart(XPredictor3 *InstancePtr);


void XPredictor3_InterruptGlobalEnable(XPredictor3 *InstancePtr);
void XPredictor3_InterruptGlobalDisable(XPredictor3 *InstancePtr);
void XPredictor3_InterruptEnable(XPredictor3 *InstancePtr, u32 Mask);
void XPredictor3_InterruptDisable(XPredictor3 *InstancePtr, u32 Mask);
void XPredictor3_InterruptClear(XPredictor3 *InstancePtr, u32 Mask);
u32 XPredictor3_InterruptGetEnabled(XPredictor3 *InstancePtr);
u32 XPredictor3_InterruptGetStatus(XPredictor3 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
