// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpredictor2.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPredictor2_CfgInitialize(XPredictor2 *InstancePtr, XPredictor2_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_ctrl_BaseAddress = ConfigPtr->Bus_ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPredictor2_Start(XPredictor2 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredictor2_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_AP_CTRL) & 0x80;
    XPredictor2_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPredictor2_IsDone(XPredictor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredictor2_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPredictor2_IsIdle(XPredictor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredictor2_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPredictor2_IsReady(XPredictor2 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredictor2_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPredictor2_EnableAutoRestart(XPredictor2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor2_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_AP_CTRL, 0x80);
}

void XPredictor2_DisableAutoRestart(XPredictor2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor2_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_AP_CTRL, 0);
}

void XPredictor2_InterruptGlobalEnable(XPredictor2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor2_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_GIE, 1);
}

void XPredictor2_InterruptGlobalDisable(XPredictor2 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor2_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_GIE, 0);
}

void XPredictor2_InterruptEnable(XPredictor2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPredictor2_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_IER);
    XPredictor2_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_IER, Register | Mask);
}

void XPredictor2_InterruptDisable(XPredictor2 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPredictor2_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_IER);
    XPredictor2_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_IER, Register & (~Mask));
}

void XPredictor2_InterruptClear(XPredictor2 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor2_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_ISR, Mask);
}

u32 XPredictor2_InterruptGetEnabled(XPredictor2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPredictor2_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_IER);
}

u32 XPredictor2_InterruptGetStatus(XPredictor2 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPredictor2_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR2_BUS_CTRL_ADDR_ISR);
}

