// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpredictor2.h"

extern XPredictor2_Config XPredictor2_ConfigTable[];

XPredictor2_Config *XPredictor2_LookupConfig(u16 DeviceId) {
	XPredictor2_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPREDICTOR2_NUM_INSTANCES; Index++) {
		if (XPredictor2_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPredictor2_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPredictor2_Initialize(XPredictor2 *InstancePtr, u16 DeviceId) {
	XPredictor2_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPredictor2_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPredictor2_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

