// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XPREDICTOR_H
#define XPREDICTOR_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xpredictor_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Bus_ctrl_BaseAddress;
} XPredictor_Config;
#endif

typedef struct {
    u32 Bus_ctrl_BaseAddress;
    u32 IsReady;
} XPredictor;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XPredictor_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XPredictor_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XPredictor_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XPredictor_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XPredictor_Initialize(XPredictor *InstancePtr, u16 DeviceId);
XPredictor_Config* XPredictor_LookupConfig(u16 DeviceId);
int XPredictor_CfgInitialize(XPredictor *InstancePtr, XPredictor_Config *ConfigPtr);
#else
int XPredictor_Initialize(XPredictor *InstancePtr, const char* InstanceName);
int XPredictor_Release(XPredictor *InstancePtr);
#endif

void XPredictor_Start(XPredictor *InstancePtr);
u32 XPredictor_IsDone(XPredictor *InstancePtr);
u32 XPredictor_IsIdle(XPredictor *InstancePtr);
u32 XPredictor_IsReady(XPredictor *InstancePtr);
void XPredictor_EnableAutoRestart(XPredictor *InstancePtr);
void XPredictor_DisableAutoRestart(XPredictor *InstancePtr);


void XPredictor_InterruptGlobalEnable(XPredictor *InstancePtr);
void XPredictor_InterruptGlobalDisable(XPredictor *InstancePtr);
void XPredictor_InterruptEnable(XPredictor *InstancePtr, u32 Mask);
void XPredictor_InterruptDisable(XPredictor *InstancePtr, u32 Mask);
void XPredictor_InterruptClear(XPredictor *InstancePtr, u32 Mask);
u32 XPredictor_InterruptGetEnabled(XPredictor *InstancePtr);
u32 XPredictor_InterruptGetStatus(XPredictor *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
