// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpredictor3.h"

extern XPredictor3_Config XPredictor3_ConfigTable[];

XPredictor3_Config *XPredictor3_LookupConfig(u16 DeviceId) {
	XPredictor3_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPREDICTOR3_NUM_INSTANCES; Index++) {
		if (XPredictor3_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPredictor3_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPredictor3_Initialize(XPredictor3 *InstancePtr, u16 DeviceId) {
	XPredictor3_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPredictor3_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPredictor3_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

