// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpredictor3.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPredictor3_CfgInitialize(XPredictor3 *InstancePtr, XPredictor3_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Bus_ctrl_BaseAddress = ConfigPtr->Bus_ctrl_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPredictor3_Start(XPredictor3 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredictor3_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_AP_CTRL) & 0x80;
    XPredictor3_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPredictor3_IsDone(XPredictor3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredictor3_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPredictor3_IsIdle(XPredictor3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredictor3_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPredictor3_IsReady(XPredictor3 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPredictor3_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPredictor3_EnableAutoRestart(XPredictor3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor3_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_AP_CTRL, 0x80);
}

void XPredictor3_DisableAutoRestart(XPredictor3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor3_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_AP_CTRL, 0);
}

void XPredictor3_InterruptGlobalEnable(XPredictor3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor3_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_GIE, 1);
}

void XPredictor3_InterruptGlobalDisable(XPredictor3 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor3_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_GIE, 0);
}

void XPredictor3_InterruptEnable(XPredictor3 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPredictor3_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_IER);
    XPredictor3_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_IER, Register | Mask);
}

void XPredictor3_InterruptDisable(XPredictor3 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPredictor3_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_IER);
    XPredictor3_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_IER, Register & (~Mask));
}

void XPredictor3_InterruptClear(XPredictor3 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPredictor3_WriteReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_ISR, Mask);
}

u32 XPredictor3_InterruptGetEnabled(XPredictor3 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPredictor3_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_IER);
}

u32 XPredictor3_InterruptGetStatus(XPredictor3 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPredictor3_ReadReg(InstancePtr->Bus_ctrl_BaseAddress, XPREDICTOR3_BUS_CTRL_ADDR_ISR);
}

